default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV["DATABASE_HOST"] || '127.0.0.1' %>
  username: <%= ENV["DATABASE_USER"] || 'postgres' %>
  password: <%= ENV["DATABASE_PASS"] || '' %>

development:
  <<: *default
  database: aeroclub_app_development

test:
  <<: *default
  database: aeroclub_app_test

production:
  <<: *default
  database: aeroclub_app_production
  username: aeroclub_app
  password: <%= ENV["AEROCLUB_APP_DATABASE_PASSWORD"] %>
